name: on push

on: push

jobs:
  pushjob:
    runs-on: ubuntu-latest
    steps:
      - name: Push triggered on any branch
        run: |
          echo "Event name: $GITHUB_EVENT_NAME"
          echo "Branch ref: $GITHUB_REF"
          echo "Commit SHA: $GITHUB_SHA"
          echo "Pushed by: $GITHUB_ACTOR"
