name: Work Flow Callee

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version to test against'
        required: false
        type: string 
        default: '20'

      working-directory:
        description: 'Folder containing package.json'
        required: false
        type: string
        default: 'sample-app'

    secrets:
      API_KEY:
        required: false
        
    outputs:
      tested_version: 
        description: 'The Node version that actually ran'
        value: ${{jobs.run-test.outputs.node-version}}

jobs:
  run-test:
    runs-on: ubuntu-latest

    outputs:
      node-version: ${{steps.report.outputs.version}}

    defaults:
      run:
        working-directory: ${{inputs.working-directory}}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: ${{inputs.node-version}}
          cache: 'npm'
          cache-dependency-path: ${{inputs.working-directory}}/package-lock.json

      - name: Run CI
        run: npm ci

      - name: Run test
        run: npm test

      - name: Reporting with the output
        id: report
        run: |
          echo "version=${{inputs.node-version}}" >> "$GITHUB_OUTPUT"

        








  
