name: Schedule Run

on:
  schedule:
    - cron: "6 * * * *"

jobs:
  schedule-task:
    runs-on: ubuntu-latest
    steps:
      - name: "Checking schedule run"
        run: echo "Schedule running successfully at 11:58 AM IST"
